"""Add completion_rate field

Revision ID: 1b6743b2e629
Revises: 95f14ceaa081
Create Date: 2023-07-02 16:31:06.298821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6743b2e629'
down_revision = '95f14ceaa081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('completion_rate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'completion_rate')
    # ### end Alembic commands ###
